name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: 'npm'
      - run: npm install

      - name: Build
        run: npm run build:prod

      - name: temporarily save docker
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: retrieve saved docker
        uses: actions/download-artifact@v3
        with:
          name: github-cd
          path: github-cd/

      - name: Display structure of downloaded files
        run: ls -R

      - name: deploy file to server
        uses: ilCollez/ssh-scp-deploy@main
        with:
          host: ${{ secrets.SERVER_IP }}
          port: 22
          username: 'root'
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          files: './dist/*'
          remote-path: '/var/www/ygo_admin'
  # build:
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 18.12.1
  #         cache: "npm"
  #     - run: |
  #         npm install
  #         npm run build:prod
  #     - name: List files in dist directory
  #       run: ls -R dist
  #     - name: deploy file to server
  #       uses: appleboy/scp-action@master
  #       with:
  #         host: ${{ secrets.SERVER_IP }}
  #         port: 22
  #         username: "root"
  #         password: ${{ secrets.SERVER_PASSWORD }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         source: "dist/**/*"
  #         target: "/var/www/ygo_admin"